#!/usr/bin/env python3
"""Bundle the v3 src/ tree into dist/theme-v3.css by following the @import
graph rooted at src/entry.css.

Design notes:
- This is the v3 bundler, intentionally separate from scripts/bundle_theme.py
  which still owns the v2.30.x dev/ -> theme.css pipeline. v3-rewrite never
  overwrites theme.css until S11 swaps them.
- @import statements outside an @layer block keep their layer assignment
  inline (e.g. `@import url(...) layer(tokens);`). This bundler inlines the
  imported file's contents wrapped in `@layer <name> { ... }` when an inline
  layer is present, otherwise it inlines verbatim.
- @layer declaration statements (no body) are passed through.
- Re-entrant imports are detected and refused.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "src" / "entry.css"
DIST = ROOT / "dist" / "theme-v3.css"

IMPORT_RE = re.compile(
    r"""@import\s+url\(\s*['"]?([^'")]+)['"]?\s*\)\s*(?:layer\(\s*([a-zA-Z0-9_-]+)\s*\))?\s*;""",
    re.IGNORECASE,
)


def strip_line_comments(line: str) -> str:
    """Remove a trailing `/* ... */` from a single line. Does not handle
    multi-line comments — the caller is responsible for those."""
    return re.sub(r"/\*.*?\*/", "", line).strip()


def is_commented_out(line: str) -> bool:
    stripped = line.strip()
    return stripped.startswith("/*") or stripped.startswith("//")


def resolve_imports(file_path: Path, visited: set[Path]) -> str:
    real = file_path.resolve()
    if real in visited:
        raise RuntimeError(f"circular @import detected: {real}")
    visited = visited | {real}
    text = real.read_text(encoding="utf-8")

    out_lines: list[str] = []
    for raw_line in text.splitlines():
        # Only treat a line as an @import directive if the directive is at the
        # *start* of the line (ignoring whitespace) AND the line is not inside
        # a comment. Commented-out @import lines (used as placeholders for
        # future steps in entry.css) must be passed through.
        if "@import" not in raw_line:
            out_lines.append(raw_line)
            continue
        if is_commented_out(raw_line):
            out_lines.append(raw_line)
            continue
        m = IMPORT_RE.search(raw_line)
        if not m:
            out_lines.append(raw_line)
            continue
        rel = m.group(1)
        layer_name = m.group(2)
        target = (real.parent / rel).resolve()
        if not target.is_file():
            raise FileNotFoundError(f"@import target not found: {rel} (from {real.relative_to(ROOT)})")
        inner = resolve_imports(target, visited)
        rel_display = target.relative_to(ROOT).as_posix()
        out_lines.append(f"/* >>> {rel_display} (layer={layer_name or 'inline'}) */")
        if layer_name:
            out_lines.append(f"@layer {layer_name} {{")
            for line in inner.splitlines():
                out_lines.append("  " + line if line else line)
            out_lines.append("}")
        else:
            out_lines.append(inner)
        out_lines.append(f"/* <<< {rel_display} */")
    return "\n".join(out_lines)


def bundle(entry: Path, dist: Path) -> int:
    if not entry.is_file():
        print(f"ERROR: entry not found: {entry}")
        return 1
    bundled = resolve_imports(entry, set())
    dist.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "/* Owen Graphite v3 — bundled from src/.\n"
        " *\n"
        " * Generated by scripts/bundle_v3.py from src/entry.css.\n"
        " * Do not hand-edit. The cascade layer order is defined in src/entry.css.\n"
        " *\n"
        " * This file is NOT a drop-in replacement for theme.css yet — the v3-rewrite\n"
        " * branch keeps theme.css on v2.30.14 until S11 swap is approved.\n"
        " */\n\n"
    )
    dist.write_text(header + bundled + "\n", encoding="utf-8")
    line_count = bundled.count("\n") + 1
    bang_count = bundled.count("!important")
    print(f"OK: bundled {dist.relative_to(ROOT)} ({line_count} lines, !important={bang_count})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entry", type=Path, default=ENTRY)
    parser.add_argument("--out", type=Path, default=DIST)
    args = parser.parse_args()
    return bundle(args.entry, args.out)


if __name__ == "__main__":
    raise SystemExit(main())
